[[redirects]]
  from = "/api/*"
  to = "http://91.186.198.179:5000/api/:splat"
  status = 200
  force = true

[[redirects]]
 from = "/uploads/*"
 to = "http://91.186.198.179:5000/uploads/:splat"
 status = 200
 force = true
